import socket
import ssl
import subprocess

from geoip2.database import Reader
from pandas import DataFrame, read_csv

# script to check a list of NTP servers for misconfigurations regarding
# usable commands like mrulist and support of the NTS protocol
#
# Requirements:
# python (tested with version 3.14.3)
# pandas (tested with version 3.0.2)
# geoip2 (tested with version 5.2.0)
#
# The input file containing the list is expected to be generated by
# the "shodan_list_creator.py" script in this repository
#
# For the addition of the "country" field the "ip-to-country-lite" database of db-ip.com is used.
# It should be positioned at "external_data/dbip-country-lite-2026-05.mmdb" as seen in the line below.

location_db_reader = Reader("external_data/dbip-country-lite-2026-05.mmdb")


def check_server(ip: str) -> dict:
    print("Checking NTS")
    nts = "Yes" if check_nts_support(ip) else "No"
    print("Checking commands")
    commands = check_commands(ip)
    mrulist = commands.get("mrulist")
    rv = commands.get("rv")
    pe = commands.get("pe")

    return {"nts": nts, "mrulist": mrulist, "rv": rv, "pe": pe}


def check_nts_support(ip: str) -> bool:
    try:
        context = ssl.create_default_context()
        context.check_hostname = False
        with socket.create_connection((ip, 4460), timeout=3) as sock:
            with context.wrap_socket(sock, server_hostname=ip):
                return True
    except Exception:
        return False


def check_commands(ip: str) -> dict:
    mrulist = "No"
    rv = "No"
    pe = "No"
    try:
        mrulist_check = check_command(ip, "mrulist")
    except Exception:
        mrulist = "unknown"
    else:
        if mrulist_check:
            mrulist = "Yes"

    try:
        rv_check = check_command(ip, "rv")
    except Exception:
        rv = "unknown"
    else:
        if rv_check:
            rv = "Yes"

    try:
        pe_check = check_command(ip, "pe")
    except Exception:
        pe = "unknown"
    else:
        if pe_check:
            pe = "Yes"

    return {
        "mrulist": mrulist,
        "rv": rv,
        "pe": pe,
    }


def check_command(ip: str, command: str) -> bool:
    print(f"Trying command {command}")
    try:
        result = subprocess.run(
            ["ntpq", "-c", command, ip],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=20,
        )
        output = result.stdout
        if "unknown" in output.lower():
            return False
        if "" == output.lower():
            return False
        return True
    except Exception:
        raise Exception("ntpq ran into a problem")


def check_country(ip: str):
    try:
        response = location_db_reader.country(ip)
        return response.country.name
    except Exception:
        return "unknown"

def check_country_iso(ip: str):
    try:
        response = location_db_reader.country(ip)
        return response.country.iso_code
    except Exception:
        return "unknown"


if __name__ == "__main__":
    input_df = read_csv("./measurement_study/data/ntp_server_list.csv", index_col=0)
    output_df = DataFrame(
        {
            "ip": [],
            "ntp_product": [],
            "ntp_version": [],
            "ntp_stratum": [],
            "nts_support": [],
            "command_mrulist": [],
            "command_rv": [],
            "command_pe": [],
            "country": [],
            "iso_code": []
        }
    )
    for i, row in input_df.iterrows():
        print(f"Now running row {i}")
        checks = check_server(str(row["ip"]))
        new_data = {
            "ip": row["ip"],
            "ntp_product": row["ntp_product"],
            "ntp_version": row["ntp_version"],
            "ntp_stratum": row["ntp_stratum"],
            "nts_support": checks.get("nts"),
            "command_mrulist": checks.get("mrulist"),
            "command_rv": checks.get("rv"),
            "command_pe": checks.get("pe"),
            "country": check_country(str(row["ip"])),
            "iso_code": check_country_iso(str(row["ip"]))
        }
        output_df.loc[len(output_df)] = new_data
    output_df.to_csv("./measurement_study/data/analyzed_servers.csv")
